import type { SettingsSection } from "renderer/stores/settings-state";

export const SETTING_ITEM_ID = {
	ACCOUNT_PROFILE: "account-profile",
	ACCOUNT_SIGNOUT: "account-signout",

	ORGANIZATION_LOGO: "organization-logo",
	ORGANIZATION_NAME: "organization-name",
	ORGANIZATION_SLUG: "organization-slug",
	ORGANIZATION_MEMBERS_LIST: "organization-members-list",
	ORGANIZATION_MEMBERS_INVITE: "organization-members-invite",
	ORGANIZATION_MEMBERS_PENDING_INVITATIONS:
		"organization-members-pending-invitations",

	APPEARANCE_THEME: "appearance-theme",
	APPEARANCE_MARKDOWN: "appearance-markdown",
	APPEARANCE_CUSTOM_THEMES: "appearance-custom-themes",
	APPEARANCE_EDITOR_FONT: "appearance-editor-font",
	APPEARANCE_TERMINAL_FONT: "appearance-terminal-font",

	RINGTONES_NOTIFICATION: "ringtones-notification",

	KEYBOARD_SHORTCUTS: "keyboard-shortcuts",
	BEHAVIOR_CONFIRM_QUIT: "behavior-confirm-quit",
	BEHAVIOR_TELEMETRY: "behavior-telemetry",
	BEHAVIOR_FILE_OPEN_MODE: "behavior-file-open-mode",
	BEHAVIOR_RESOURCE_MONITOR: "behavior-resource-monitor",
	BEHAVIOR_OPEN_LINKS_IN_APP: "behavior-open-links-in-app",

	GIT_BRANCH_PREFIX: "git-branch-prefix",
	GIT_DELETE_LOCAL_BRANCH: "git-delete-local-branch",
	GIT_WORKTREE_LOCATION: "git-worktree-location",

	AGENTS_ENABLED: "agents-enabled",
	AGENTS_COMMANDS: "agents-commands",
	AGENTS_TASK_PROMPTS: "agents-task-prompts",

	TERMINAL_PRESETS: "terminal-presets",
	TERMINAL_QUICK_ADD: "terminal-quick-add",
	TERMINAL_SESSIONS: "terminal-sessions",
	TERMINAL_LINK_BEHAVIOR: "terminal-link-behavior",

	MODELS_ANTHROPIC: "models-anthropic",
	MODELS_OPENAI: "models-openai",

	INTEGRATIONS_LINEAR: "integrations-linear",
	INTEGRATIONS_GITHUB: "integrations-github",
	INTEGRATIONS_SLACK: "integrations-slack",

	BILLING_OVERVIEW: "billing-overview",
	BILLING_PLANS: "billing-plans",
	BILLING_USAGE: "billing-usage",

	PROJECT_NAME: "project-name",
	PROJECT_PATH: "project-path",
	PROJECT_SCRIPTS: "project-scripts",
	PROJECT_BRANCH_PREFIX: "project-branch-prefix",
	PROJECT_WORKTREE_LOCATION: "project-worktree-location",
	PROJECT_IMPORT_WORKTREES: "project-import-worktrees",
	PROJECT_ENV_VARS: "project-env-vars",

	API_KEYS_LIST: "api-keys-list",
	API_KEYS_GENERATE: "api-keys-generate",

	PERMISSIONS_FULL_DISK_ACCESS: "permissions-full-disk-access",
	PERMISSIONS_ACCESSIBILITY: "permissions-accessibility",
	PERMISSIONS_MICROPHONE: "permissions-microphone",
	PERMISSIONS_APPLE_EVENTS: "permissions-apple-events",
	PERMISSIONS_LOCAL_NETWORK: "permissions-local-network",

	SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY:
		"security-expose-host-service-via-relay",

	SSH_HOSTS: "ssh-hosts",
} as const;

export type SettingItemId =
	(typeof SETTING_ITEM_ID)[keyof typeof SETTING_ITEM_ID];

export interface SettingsItem {
	id: SettingItemId;
	section: SettingsSection;
	title: string;
	description: string;
	keywords: string[];
}

export const SETTINGS_ITEMS: SettingsItem[] = [
	{
		id: SETTING_ITEM_ID.ACCOUNT_PROFILE,
		section: "account",
		title: "Profile",
		description: "Your profile information",
		keywords: [
			"account",
			"name",
			"email",
			"avatar",
			"user",
			"profile",
			"picture",
			"photo",
			"me",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_SIGNOUT,
		section: "account",
		title: "Sign Out",
		description: "Sign out of your account",
		keywords: [
			"account",
			"sign out",
			"logout",
			"log out",
			"disconnect",
			"leave",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_LOGO,
		section: "organization",
		title: "Organization Logo",
		description: "Upload and manage your organization's logo",
		keywords: [
			"organization",
			"logo",
			"image",
			"branding",
			"upload",
			"icon",
			"picture",
			"avatar",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_NAME,
		section: "organization",
		title: "Organization Name",
		description: "Change your organization's display name",
		keywords: [
			"organization",
			"name",
			"rename",
			"title",
			"company",
			"team name",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_SLUG,
		section: "organization",
		title: "Organization Slug",
		description: "Your organization's unique identifier",
		keywords: [
			"organization",
			"slug",
			"url",
			"identifier",
			"subdomain",
			"link",
			"unique",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_LIST,
		section: "organization",
		title: "Team Members",
		description: "View and manage team members and their roles",
		keywords: [
			"organization",
			"members",
			"team",
			"users",
			"roles",
			"people",
			"collaborators",
			"permissions",
			"access",
			"admin",
			"owner",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_INVITE,
		section: "organization",
		title: "Invite Members",
		description: "Invite new members to your organization",
		keywords: [
			"organization",
			"members",
			"invite",
			"add",
			"new member",
			"team",
			"share",
			"collaborate",
			"email",
			"send invite",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_PENDING_INVITATIONS,
		section: "organization",
		title: "Pending Invitations",
		description: "View and manage pending organization invitations",
		keywords: [
			"organization",
			"members",
			"invite",
			"invitation",
			"pending",
			"team",
			"waiting",
			"sent",
			"cancel",
			"resend",
			"email",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_THEME,
		section: "appearance",
		title: "Theme",
		description: "Choose your theme",
		keywords: [
			"appearance",
			"theme",
			"dark",
			"light",
			"dark mode",
			"light mode",
			"colors",
			"night",
			"system",
			"visual",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_MARKDOWN,
		section: "appearance",
		title: "Markdown Style",
		description: "Rendering style for markdown files",
		keywords: [
			"appearance",
			"markdown",
			"style",
			"tufte",
			"rendering",
			"preview",
			"format",
			"display",
			"md",
			"readme",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_CUSTOM_THEMES,
		section: "appearance",
		title: "Custom Themes",
		description: "Import custom theme files",
		keywords: [
			"appearance",
			"custom",
			"themes",
			"import",
			"json",
			"color scheme",
			"upload",
			"personalize",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_EDITOR_FONT,
		section: "appearance",
		title: "Editor Font",
		description: "Font used in diff views and file editors",
		keywords: [
			"appearance",
			"font",
			"family",
			"size",
			"editor",
			"diff",
			"mono",
			"monospace",
			"typography",
			"custom",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_TERMINAL_FONT,
		section: "appearance",
		title: "Terminal Font",
		description: "Font used in terminal panels",
		keywords: [
			"appearance",
			"font",
			"family",
			"size",
			"terminal",
			"mono",
			"monospace",
			"typography",
			"custom",
			"nerd",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_NOTIFICATION,
		section: "ringtones",
		title: "Notification Sound",
		description: "Choose the notification sound for completed tasks",
		keywords: [
			"notifications",
			"notification",
			"sound",
			"ringtone",
			"audio",
			"alert",
			"bell",
			"tone",
			"complete",
			"done",
			"finished",
			"chime",
			"mute",
			"volume",
		],
	},
	{
		id: SETTING_ITEM_ID.KEYBOARD_SHORTCUTS,
		section: "keyboard",
		title: "Keyboard Shortcuts",
		description: "View and customize keyboard shortcuts",
		keywords: [
			"keyboard",
			"shortcuts",
			"hotkeys",
			"keys",
			"bindings",
			"keybindings",
			"commands",
			"ctrl",
			"cmd",
			"alt",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_CONFIRM_QUIT,
		section: "behavior",
		title: "Confirm before quitting",
		description: "Show a confirmation dialog when quitting the app",
		keywords: [
			"features",
			"confirm",
			"quit",
			"quitting",
			"exit",
			"close",
			"dialog",
			"warning",
			"prompt",
			"unsaved",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_DELETE_LOCAL_BRANCH,
		section: "git",
		title: "Delete local branch on workspace removal",
		description:
			"Also delete the local git branch when deleting a worktree workspace",
		keywords: [
			"git",
			"delete",
			"branch",
			"local",
			"worktree",
			"workspace",
			"remove",
			"cleanup",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_BRANCH_PREFIX,
		section: "git",
		title: "Branch Prefix",
		description: "Default prefix for new branch names",
		keywords: [
			"git",
			"branch",
			"prefix",
			"naming",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_TELEMETRY,
		section: "behavior",
		title: "Send anonymous usage data",
		description: "Help improve Superset by sending anonymous usage data",
		keywords: [
			"telemetry",
			"analytics",
			"tracking",
			"privacy",
			"data",
			"usage",
			"anonymous",
			"metrics",
			"opt out",
			"disable",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_FILE_OPEN_MODE,
		section: "behavior",
		title: "File open mode",
		description:
			"Choose how files open when clicked in the file tree or changes view",
		keywords: [
			"file",
			"open",
			"mode",
			"split",
			"pane",
			"tab",
			"new tab",
			"split pane",
			"viewer",
			"behavior",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_RESOURCE_MONITOR,
		section: "behavior",
		title: "Resource monitor",
		description:
			"Show CPU and memory usage for workspaces and terminal sessions in the top bar",
		keywords: [
			"features",
			"resource",
			"monitor",
			"cpu",
			"memory",
			"ram",
			"usage",
			"performance",
			"process",
			"terminal",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_WORKTREE_LOCATION,
		section: "git",
		title: "Worktree location",
		description: "Base directory where new worktrees are created on disk",
		keywords: [
			"git",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"base",
			"default",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_OPEN_LINKS_IN_APP,
		section: "behavior",
		title: "Open links in app browser",
		description:
			"Open links from chat and terminal in the built-in browser instead of your default browser",
		keywords: [
			"browser",
			"links",
			"in-app",
			"external",
			"open",
			"chat",
			"terminal",
			"url",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_ENABLED,
		section: "agents",
		title: "Enabled agents",
		description: "Control which agents appear in workspace launchers",
		keywords: [
			"agents",
			"enabled",
			"launcher",
			"dropdown",
			"visible",
			"show",
			"hide",
			"superset chat",
			"claude",
			"codex",
			"pi",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_COMMANDS,
		section: "agents",
		title: "Agent commands",
		description: "Configure no-prompt and prompt launch commands",
		keywords: [
			"agents",
			"commands",
			"prompt command",
			"terminal",
			"claude",
			"codex",
			"gemini",
			"opencode",
			"pi",
			"copilot",
			"cursor",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_TASK_PROMPTS,
		section: "agents",
		title: "Task prompt templates",
		description: "Configure task prompt templates for agent launches",
		keywords: [
			"agents",
			"task prompt",
			"template",
			"variables",
			"prompt",
			"task",
			"superset chat",
			"launch",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_PRESETS,
		section: "terminal",
		title: "Terminal Presets",
		description: "Manage your terminal presets",
		keywords: [
			"terminal",
			"preset",
			"presets",
			"commands",
			"agent",
			"launch",
			"default",
			"startup",
			"config",
			"shell",
			"run",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_QUICK_ADD,
		section: "terminal",
		title: "Quick Add Templates",
		description: "Pre-configured terminal presets",
		keywords: [
			"terminal",
			"quick",
			"add",
			"template",
			"claude",
			"codex",
			"gemini",
			"cursor",
			"opencode",
			"pi",
			"ai",
			"assistant",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_SESSIONS,
		section: "terminal",
		title: "Active Sessions",
		description: "View and manage active terminal sessions",
		keywords: [
			"terminal",
			"sessions",
			"active",
			"running",
			"kill",
			"terminate",
			"process",
			"stop",
			"manage",
			"pty",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_LINK_BEHAVIOR,
		section: "terminal",
		title: "Link Behavior",
		description: "How to open links from terminal",
		keywords: [
			"terminal",
			"link",
			"click",
			"open",
			"external",
			"editor",
			"file",
			"url",
			"path",
			"cmd",
			"ctrl",
			"browser",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_ANTHROPIC,
		section: "models",
		title: "Anthropic Model Auth",
		description: "Connect Anthropic for workspace naming and small model tasks",
		keywords: [
			"models",
			"anthropic",
			"claude",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_OPENAI,
		section: "models",
		title: "OpenAI Model Auth",
		description: "Connect OpenAI for supported model tasks",
		keywords: [
			"models",
			"openai",
			"gpt",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_LINEAR,
		section: "integrations",
		title: "Linear",
		description: "Sync issues bidirectionally with Linear",
		keywords: [
			"integrations",
			"linear",
			"issues",
			"tasks",
			"sync",
			"connect",
			"connected",
			"project management",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_GITHUB,
		section: "integrations",
		title: "GitHub",
		description: "Connect repos and sync pull requests",
		keywords: [
			"integrations",
			"github",
			"repos",
			"repositories",
			"pull requests",
			"pr",
			"sync",
			"connect",
			"connected",
			"version control",
			"git",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_SLACK,
		section: "integrations",
		title: "Slack",
		description: "Manage tasks from Slack conversations",
		keywords: [
			"integrations",
			"slack",
			"messages",
			"conversations",
			"tasks",
			"chat",
			"sync",
			"connect",
			"connected",
			"communication",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_OVERVIEW,
		section: "billing",
		title: "Current plan",
		description: "View your current subscription and usage",
		keywords: [
			"billing",
			"plan",
			"subscription",
			"pro",
			"free",
			"enterprise",
			"current",
			"payment",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_PLANS,
		section: "billing",
		title: "All plans",
		description: "Compare and upgrade plans",
		keywords: [
			"billing",
			"upgrade",
			"pricing",
			"plans",
			"pro",
			"enterprise",
			"compare",
			"features",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_USAGE,
		section: "billing",
		title: "Usage limits",
		description: "Track workspace and user limits",
		keywords: [
			"billing",
			"usage",
			"limits",
			"workspaces",
			"users",
			"quota",
			"seats",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_NAME,
		section: "project",
		title: "Project Name",
		description: "The name of this project",
		keywords: ["project", "name", "rename", "title", "label"],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_PATH,
		section: "project",
		title: "Repository Path",
		description: "The file path to this project",
		keywords: [
			"project",
			"path",
			"repository",
			"folder",
			"directory",
			"location",
			"git",
			"repo",
			"root",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_SCRIPTS,
		section: "project",
		title: "Scripts",
		description: "Setup and teardown scripts for workspaces",
		keywords: [
			"project",
			"scripts",
			"setup",
			"teardown",
			"bash",
			"shell",
			"automation",
			"hooks",
			"init",
			"initialize",
			"cleanup",
			"onboarding",
			"config",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_BRANCH_PREFIX,
		section: "project",
		title: "Branch Prefix",
		description: "Override the default branch prefix for this project",
		keywords: [
			"project",
			"branch",
			"prefix",
			"naming",
			"git",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
			"override",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_WORKTREE_LOCATION,
		section: "project",
		title: "Worktree Location",
		description: "Override the global worktree directory for this project",
		keywords: [
			"project",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"override",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_IMPORT_WORKTREES,
		section: "project",
		title: "Import Worktrees",
		description: "Import existing worktrees from disk into Superset",
		keywords: [
			"project",
			"import",
			"worktree",
			"worktrees",
			"workspace",
			"workspaces",
			"external",
			"existing",
			"disk",
			"add",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_ENV_VARS,
		section: "project",
		title: "Environment Variables",
		description: "Manage environment variables and secrets for cloud sandboxes",
		keywords: [
			"environment",
			"variables",
			"secrets",
			"env",
			"cloud",
			"sandbox",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_LIST,
		section: "apikeys",
		title: "API Keys",
		description: "Manage API keys for MCP server access",
		keywords: [
			"api",
			"key",
			"keys",
			"mcp",
			"claude",
			"integration",
			"external",
			"access",
			"token",
			"authentication",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_GENERATE,
		section: "apikeys",
		title: "Generate API Key",
		description: "Create new API keys for external integrations",
		keywords: [
			"api",
			"key",
			"generate",
			"create",
			"new",
			"mcp",
			"claude desktop",
			"claude code",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_FULL_DISK_ACCESS,
		section: "permissions",
		title: "Full Disk Access",
		description:
			"Persistent access to Documents, Downloads, Desktop, and iCloud from terminal sessions",
		keywords: [
			"permissions",
			"full disk access",
			"fda",
			"files",
			"documents",
			"downloads",
			"desktop",
			"icloud",
			"macos",
			"security",
			"privacy",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_ACCESSIBILITY,
		section: "permissions",
		title: "Accessibility",
		description:
			"Send keystrokes, manage windows, and control other applications",
		keywords: [
			"permissions",
			"accessibility",
			"a11y",
			"keystrokes",
			"window management",
			"macos",
			"security",
			"privacy",
			"trusted",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_MICROPHONE,
		section: "permissions",
		title: "Microphone",
		description: "Use voice transcription and push-to-talk features",
		keywords: [
			"permissions",
			"microphone",
			"mic",
			"voice",
			"transcription",
			"audio",
			"recording",
			"push to talk",
			"codex",
			"privacy",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_APPLE_EVENTS,
		section: "permissions",
		title: "Automation",
		description: "Run terminal commands and interact with other applications",
		keywords: [
			"permissions",
			"automation",
			"apple events",
			"applescript",
			"macos",
			"security",
			"privacy",
			"system events",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_LOCAL_NETWORK,
		section: "permissions",
		title: "Local Network",
		description: "Discover and connect to development servers on your network",
		keywords: [
			"permissions",
			"local network",
			"bonjour",
			"mdns",
			"macos",
			"security",
			"privacy",
			"development servers",
		],
	},
	{
		id: SETTING_ITEM_ID.SSH_HOSTS,
		section: "ssh",
		title: "SSH Hosts",
		description: "Configure SSH hosts for remote development",
		keywords: [
			"ssh",
			"remote",
			"host",
			"server",
			"connection",
			"key",
			"private key",
			"forward agent",
			"port",
			"username",
			"development",
		],
	},
	{
		id: SETTING_ITEM_ID.SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY,
		section: "security",
		title: "Allow remote workspaces to access this device via relay",
		description:
			"Controls whether remote workspaces can reach your local host service through the Superset relay",
		keywords: [
			"security",
			"relay",
			"remote",
			"workspace",
			"expose",
			"lockdown",
			"network",
			"inbound",
			"host service",
			"tunnel",
			"attack surface",
		],
	},
];

export function searchSettings(query: string): SettingsItem[] {
	if (!query.trim()) return SETTINGS_ITEMS;

	const q = query.toLowerCase();
	return SETTINGS_ITEMS.filter(
		(item) =>
			item.title.toLowerCase().includes(q) ||
			item.description.toLowerCase().includes(q) ||
			item.keywords.some((kw) => kw.toLowerCase().includes(q)),
	);
}

export function getMatchCountBySection(
	query: string,
): Partial<Record<SettingsSection, number>> {
	const matches = searchSettings(query);
	const counts: Partial<Record<SettingsSection, number>> = {};

	for (const item of matches) {
		counts[item.section] = (counts[item.section] || 0) + 1;
	}

	return counts;
}

export function getMatchingItemsForSection(
	query: string,
	section: SettingsSection,
): SettingsItem[] {
	return searchSettings(query).filter((item) => item.section === section);
}

export function isItemVisible(
	itemId: SettingItemId,
	visibleItems: SettingItemId[] | null | undefined,
): boolean {
	return !visibleItems || visibleItems.includes(itemId);
}
